image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [541.5039 ,   0.     , 338.62424,
           0.     , 541.49841, 249.88877,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.113971, -0.126137, 0.001586, 0.010971, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [554.09308,   0.     , 344.73218,   0.     ,
           0.     , 560.45398, 250.08947,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
